functionsDirectory = "C:\\Users\\dwrek\\100X_DEPLOYMENT\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []

[build]
publish = "C:\\Users\\dwrek\\100X_DEPLOYMENT"
publishOrigin = "default"
functions = "C:\\Users\\dwrek\\100X_DEPLOYMENT\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/"
to = "/platform.html"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/screening"
to = "/platform.html"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/screening.html"
to = "/platform.html"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]