#!/bin/bash
# FULL SYSTEM REPORT TO GITHUB - RUN THIS NOW

echo "=========================================="
echo "FULL SYSTEM REPORT TO GITHUB"
echo "=========================================="
echo ""

# Get info
echo "Computer name/ID: "
read COMPUTER_ID

echo "What are you working on: "
read TASK

# Create report directory
mkdir -p GITHUB_REPORTS
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT="GITHUB_REPORTS/${COMPUTER_ID}-${TIMESTAMP}.md"

# Generate full report
cat > "$REPORT" <<EOF
# SYSTEM REPORT: $COMPUTER_ID
**Timestamp:** $(date -Iseconds)
**Task:** $TASK

## Git Status
\`\`\`
$(git status)
\`\`\`

## Current Branch
\`\`\`
$(git branch --show-current)
\`\`\`

## Recent Commits (last 5)
\`\`\`
$(git log -5 --oneline)
\`\`\`

## Files Changed
\`\`\`
$(git status --short)
\`\`\`

## Active Instances (if any)
\`\`\`
$(ls TRINITY_COORDINATION/active_instances/*.json 2>/dev/null | xargs cat 2>/dev/null || echo "No instances registered locally")
\`\`\`

## Instance Reports (if any)
\`\`\`
$(ls TRINITY_HUB_DATA/instance_reports/*.json 2>/dev/null | xargs cat 2>/dev/null || echo "No instance reports yet")
\`\`\`

## Computer Environment
- Hostname: $(hostname)
- User: $(whoami)
- Working Dir: $(pwd)
- Python: $(python3 --version 2>/dev/null || echo "Not found")
- Git: $(git --version)

## Status
✅ Report generated and ready to push to GitHub

---
*Generated by: $COMPUTER_ID at $(date)*
EOF

echo "✅ Report created: $REPORT"
echo ""

# Push to GitHub
echo "📤 Pushing to GitHub..."
git add GITHUB_REPORTS/
git commit -m "System report from $COMPUTER_ID - $TASK"
git push origin claude/autonomous-contact-test-011CUtYhH6FjHJiY9ZgmCLtR

echo ""
echo "=========================================="
echo "✅ REPORT SENT TO GITHUB"
echo "=========================================="
echo ""
echo "Your report: $REPORT"
echo ""
echo "To see ALL reports from ALL computers:"
echo "  ./SEE_ALL_GITHUB_REPORTS.sh"
echo ""
